kind: Pod
apiVersion: v1
metadata:
  name: Tolerations
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoExecute"